version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    # other configuration for the front-end service

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # other configuration for the back-end service

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: ver_tech_fellowship
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    # other configuration for the database service
